name: Waka

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Profile Readme with metrics
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Wakatime stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.CLASSIC_ACCESS_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_TIMEZONE: "False"
          SHOW_PROJECTS: "True"
          SHOW_LOC_CHART: "False"
          SYMBOL_VERSION: 2

      - name: Update README.md with Wakatime stats
        run: |
          sed -i '/<!--START_SECTION:waka-->/,/<\!--END_SECTION:waka-->/d' README.md
          echo "## Wakatime Stats" >> README.md
          echo "<!--START_SECTION:waka-->" >> README.md
          echo "Total coding time this week: ${{ steps.wakatime.outputs.weekly }} hours" >> README.md
          echo "Repositories worked on:" >> README.md
          echo "${{ steps.wakatime.outputs.projects }}" >> README.md
          echo "<!--END_SECTION:waka-->" >> README.md

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
