name: Waka

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Profile Readme with metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.CLASSIC_ACCESS_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_TIMEZONE: "False"
          SHOW_PROJECTS: "True"
          SHOW_LOC_CHART: "False"
          SYMBOL_VERSION: 2
          